id: P07574473
initial_creation_type: ocr
source_metadata:
  volumes:
    9f1bd5a75b4642a78f0f67dfb79ffdb4:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: དཔལ་ཨུ་རྒྱན་དུ་ཚོགས་འཁོར་བྱས་པའི་དུས་སུ་རྣལ་འབྱོར་པ་གྲུབ་པ་ཐོབ་པ་བཞི་བཅུས་རྡོ་རྗེའི་མགུར་བཞེངས་པ་ཉམས་ཀྱི་མན་ངག་ཐིག་ལེ་གསེར་གྱི་ཕྲེང་བ།
      total_pages: 1953
      volume_number: 27
